apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: iperf-client
spec:
    replicas: 50
    template:
        metadata:
            name: iperf-client
            labels:
                app: iperf-client
        spec:
            containers:
            - name: test
              image: tolriaz/iperf
              command: ["/bin/bash"]
              args: ["-c","cd /usr/share/nginx/html/ && ./client_iperf.sh 220.149.13.191 10 5001"]
              ports:
              - name: http-port
                containerPort: 80
              resources:
                  requests:
                      cpu: 200m
