apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tcp-client
spec:
    replicas: 1
    template:
        metadata:
            name: tcp-client
            labels:
                app: tcp-client
        spec:
            containers:
            - name: test
              image: tolriaz/iperf:TCP
              command: ["/bin/bash"]
              args: ["-c","cd /usr/share/nginx/html/ && ./client_iperf.sh 220.149.13.192 10 30021"]
              ports:
              - name: http-port
                containerPort: 80
