apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: udp-server
spec:
    replicas: 1
    template:
        metadata:
            name: udp-server
            labels:
                app: udp-server
        spec:
            containers:
            - name: udp-server
              image: tolriaz/iperf:S
              imagePullPolicy: Always
              ports:
              - containerPort: 10002
                protocol: TCP
              resources:
                  requests:
                      cpu: 200m

