apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: itest
spec:
    replicas: 30
    template:
        metadata:
            name: itest
            labels:
                app: itest
        spec:
            containers:
            - name: itest
              image: tolriaz/iperf:TCP
              command: ["/bin/bash"]
              args: ["-c","cd /usr/share/nginx/html/ && ./client_iperf.sh 220.149.13.192 10 30024"]
              ports:
              - name: http-port
                containerPort: 80
              resources:
                  requests:
                      cpu: 200m
