apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: udp-server
spec:
    replicas: 1
    template:
        metadata:
            name: udp-server
            labels:
                app: udp-server
        spec:
            containers:
            - name: udp-server
              image: tolriaz/iperf:S
              imagePullPolicy: Always
              ports:
              - containerPort: 10001
                protocol: UDP
              resources:
                  requests:
                      cpu: 200m

---
kind: Service
apiVersion: v1
metadata:
  name: udp-svc
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: udp-server
  ports:
  - protocol: UDP
    port: 10001
    nodePort: 30000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: udp-server
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: udp-server
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 50

