apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: wget-client
spec:
    replicas: 10
    template:
        metadata:
            name: wget-client
            labels:
                app: wget-client
        spec:
            containers:
            - name: test
              image: tolriaz/wget
              imagePullPolicy: Always
              command: ["/bin/bash"]
              args: ["-c", "./wget.sh 36000 220.149.13.191 5", "cat index.html"]
              ports:
              - name: http-port
                containerPort: 8080
              resources:
                requests:
                  cpu: 500m

---
kind: Service
apiVersion: v1
metadata:
  name: wget-svc
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: wget-client
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30050

