apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: wget-client
spec:
    replicas: 1
    template:
        metadata:
            name: wget-client
            labels:
                app: wget-client
        spec:
            containers:
            - name: test
              image: tolriaz/wget
              imagePullPolicy: Always
              command: ["/bin/bash"]
              args: ["-c", "./wget.sh 60 220.149.13.191 60"]
              ports:
              - name: http-port
                containerPort: 5050
---
kind: Service
apiVersion: v1
metadata:
  name: wget-svc
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: wget-client
  ports:
  - protocol: TCP
    port: 5050
    nodePort: 30050

