apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: test
spec:
    replicas: 3
    template:
        metadata:
            name: test
            labels:
                app: test
        spec:
            containers:
            - name: test
              image: gcr.io/google_containers/hpa-example
              ports:
              - name: http-port
                containerPort: 80
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: test
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: test
    minReplicas: 1
    maxReplicas: 15
    targetCPUUtilizationPercentage: 100
