apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: test
    annotations:
       kubernetes.io/ingress-bandwidth: 1M
       kubernetes.io/egress-bandwidth: 1M
spec:
    replicas: 1
    template:
        metadata:
            name: test
            labels:
                app: test
        spec:
            containers:
            - name: test
              image: tolriaz/iperf:C
              ports:
              - name: http-port
                containerPort: 80
              resources:
                  requests:
                      cpu: 200m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: test
spec:
  scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: test
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metric:
        name: container_receive_1m
      target:
        type: AverageValue
        averageValue: 100m
