apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: bandwidth-test
  annotations: 
    kubernetes.io/ingress-bandwidth: "500M"
    kubernetes.io/egress-bandwidth: "500M"
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
        env: beta
    spec:
      containers:
      - name: bandwidth-test
        image: tolriaz/iperf
        ports:
        - containerPort: 80
          protocol: TCP
#      nodeSelector:
#        kubernetes.io/hostname: "kube-node2"
