apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  annotations: 
    kubernetes.io/ingress-bandwidth: "10000M"
    kubernetes.io/egress-bandwidth: "10000M"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        env: beta
    spec:
      containers:
      - name: bandwidth-test
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: "kube-node2"
