apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
        task: monitoring
    spec:
      containers:
      - image: influxdb
        name: influxdb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 30024
  selector:
    app: influxdb
