apiVersion: v1
kind: Service
metadata:
  name: svc-np 
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
    nodePort: 30031
#  externalIPs: ["220.149.13.192"]
