apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
  annotations:
    kubernetes.io/ingress-bandwidth: 100M
    kubernetes.io/egress-bandwidth: 100M
spec:
  containers:
  - name: myapp-container
    image: nginx

    nodeSelector:
      kubernetes.io/hostname: "kube-node2"
